name: Deploy React App to GitHub Pages

on:
    push:
        branches:
            - main # Trigger deployment on push to 'main' branch only

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "20.x"

            - name: Install dependencies
              run: yarn install

            - name: Build the app
              run: yarn build

            - name: Set up Git user
              run: |
                  git config user.name "Irving Zamora"
                  git config user.email "irvingzamora28@gmail.com"

            - name: Deploy to GitHub Pages
              run: yarn deploy
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
